### ISSUE TITLE
Workflow for documentation is not working

### ISSUE THREAD

**Issue by meomancer** [kartoza/tomorrownow_gap#108]
# Problem
Workflow for documentation is not working

# Tasks
- [ ] Delete that is not needed between
https://github.com/kartoza/tomorrownow_gap/blob/main/.github/workflows/mkdocs.yml
https://github.com/kartoza/tomorrownow_gap/blob/main/.github/workflows/BuildMKDocsAndPublishToGithubPages.yml

- [x] Create **docs** branch
- [ ] Fix the git workflow by pushing to **docs** branch
- [ ] If the git workflow on **docs** branch is working, create PR from **docs** to **main**

**Comment by meomancer** [comment]
This is already fixed, thank you so much @ketankartoza
